Repository team-haribo/GOMS-iOS, pull requests merged in 2023-08, with the labels that each got.

#259 🔀 :: 258 bug library recovery
  .DS_Store
  .package.resolved
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Resources/Extension/GOMSQrCode.swift
  GOMS-iOS/Sources/Data/Services/Account/AccountServices 2.swift
  GOMS-iOS/Sources/Data/Services/Auth/AuthServices.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  Project.swift
Labels: 🐞 BugFix

#261 🔀 :: Project.swift에 info.plist, Assest 추가
  .DS_Store
  Derived/InfoPlists/GOMS-iOS-Info.plist
  Derived/Sources/TuistBundle+GOMSIOS.swift
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Info.plist
  GOMS-iOS/Resources/Font/SF-Pro-Text-Bold.otf
  GOMS-iOS/Resources/Font/SF-Pro-Text-Medium.otf
  GOMS-iOS/Resources/Font/SF-Pro-Text-Regular.otf
  GOMS-iOS/Resources/Font/SF-Pro-Text-Semibold.otf
  Project.swift
  보관함/.DS_Store
  보관함/ColorLogo.svg
  보관함/Ellipse 9.svg
  보관함/Group 50.svg
  보관함/Group 71.png
  보관함/Group 71.svg
  보관함/Group 78.svg
  보관함/Group 92.svg
  보관함/Icon.svg
  보관함/Logo.png
  보관함/Mask group.svg
  보관함/Vector.svg
  보관함/adminImage.svg
  보관함/adminOuting.svg
  보관함/chevron.backward.svg
  보관함/dummyImage.svg
  보관함/homeUndraw.svg
  보관함/logoutIcon.svg
  보관함/main_recycler_item_profile.svg
  보관함/outing_searching_icon.svg
  보관함/selectHome.svg
  보관함/selectOuting.svg
  보관함/selectRequset.svg
  보관함/selectedAdminQRCode.svg
  보관함/selectedQRCode.svg
  보관함/undraw_no_data_re_kwbl 2.svg
  보관함/undraw_working_re_ddwy 2.svg
  보관함/unselectedAdminQRCode.svg
  보관함/􀈎.svg
  보관함/􀎟.svg
  보관함/􀎹.svg
  보관함/􀎻.svg
  보관함/􀓤.svg
  보관함/􁏜.svg
Labels: 🐞 BugFix

#263 🔀 :: 262 add clientid redirecturi
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Info.plist
  GOMS-iOS/Sources/Data/General/BaseURL.swift
  GOMS-iOS/Sources/Presentation/Auth/Intro/ViewModel/IntroViewModel.swift
Labels: ✨ Feature

#266 🔀 :: 247 splashpage
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS/Resources/Assets.xcassets/Images/Icon2.imageset/Contents.json
  GOMS-iOS/Resources/Assets.xcassets/Images/Icon2.imageset/Image.png
  GOMS-iOS/Resources/Base.lproj/LaunchScreen.storyboard
  GOMS-iOS/Sources/Application/Flow/SceneDelegate.swift
  GOMS-iOS/Sources/Presentation/Main/Splash/SplashViewController.swift
Labels: ✨ Feature

#267 🔀 :: 249 Add update dialog
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS/Info.plist
  GOMS-iOS/Sources/Application/Flow/SceneDelegate.swift
Labels: ✨ Feature

#269 🔀 :: 268 Siren 의존성 추가
  .package.resolved
  GOMS-iOS.xcodeproj/project.pbxproj
  Project.swift
Labels: 🐞 BugFix

#271 🔀 :: 268 Siren Dependency
  .package.resolved
  GOMS-iOS.xcodeproj/project.pbxproj
  Project.swift
Labels: 🐞 BugFix

#275 🔀 :: TabBar 두 번 나오는 버그 해결
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
Labels: 🐞 BugFix

#277 🔀 :: Home View 404 Error
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Data/General/BaseURL.swift
Labels: 🐞 BugFix

#279 🔀 :: ReactorKit Version Downgrade
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  Project.swift
Labels: 🔨 Refactor

#281 🔀 :: Add Admin Func
  .package.resolved
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Resources/Extension/GOMSColor.swift
  GOMS-iOS/Resources/Extension/GOMSImageView.swift
  GOMS-iOS/Resources/Extension/UINavigationBar.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  GOMS-iOS/Sources/Application/Flow/Step/GOMSStep.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/MakeQRModel.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/SearchModel.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/StudentInfoModel.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/EditAuthorityRequest.swift
  GOMS-iOS/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift .swift
  GOMS-iOS/Sources/Presentation/Base/BaseViewController.swift
  GOMS-iOS/Sources/Presentation/Main/EditUserModal/View/EditModalViewController.swift
  GOMS-iOS/Sources/Presentation/Main/EditUserModal/ViewModel/EditUserModalViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/Home/View/HomeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Home/ViewModel/HomeViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/Cell/OutingTableViewCell.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/ViewModel/OutingViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/ViewModel/QRCodeModel.swift
  GOMS-iOS/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
  GOMS-iOS/Sources/Presentation/Main/SearchModal/ViewModel/SearchModalViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/Cell/StudentInfoCell.swift .swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/View/StudentInfoViewController.swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/ViewModel/StudentInfoViewModel.swift
  GOMS-iOS/Sources/Presentation/TabBar/GOMSTabBar.swift
  Project.swift
Labels: 🐞 BugFix

#283 🔀 :: 282 qrcode library change
  .package.resolved
  Derived/Sources/TuistBundle+GOMSIOS.swift
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/xcshareddata/xcschemes/GOMS-iOS.xcscheme
  GOMS-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS.xcworkspace/xcshareddata/xcschemes/GOMS-iOS-Workspace.xcscheme
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Info.plist
  GOMS-iOS/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  GOMS-iOS/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  Project.swift
Labels: 🔨 Refactor

#289 🔀 :: 외출 시 바로 복귀하기로 변경
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Presentation/Main/Home/View/HomeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Home/ViewModel/HomeViewModel.swift
Labels: 🔨 Refactor

#287 🔀 : :Change QRCode Scan View
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Resources/Extension/UINavigationBar.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/ViewModel/QRCodeModel.swift
Labels: 🔨 Refactor

#291 🔀 :: QRCode 예외처리
  .DS_Store
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Info.plist
  GOMS-iOS/Sources/Presentation/Main/QRCode/ViewModel/QRCodeModel.swift
Labels: 🐞 BugFix
