Repository team-haribo/GOMS-iOS, pull requests merged in 2023-07, with the labels that each got.

#218 217 Add Main Refresh
  GOMS-iOS/Sources/Presentation/Main/Home/View/HomeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feature

#220 🔀 :: 219 강제 언래핑 제거
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Resources/Extension/GOMSRefreshToken.swift
  GOMS-iOS/Sources/Presentation/Main/Home/ViewModel/HomeViewModel.swift
Labels: 🔨 Refactor

#222 🔀 :: 221 add outing time
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Data/Model/Outing/OutingListModel.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/Cell/OutingTableViewCell.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
Labels: 📬 API

#227 🔀 :: Update README.md
  README.md
Labels: 📃 Docs

#231 🔀 :: 다크모드 시 검색 텍스트 버그 해결
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
Labels: 🐞 BugFix

#233 🔀 :: 외출 시간 안 보이는 버그 해결
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Presentation/Main/Outing/Cell/OutingTableViewCell.swift
Labels: 🐞 BugFix

#238 🔀 :: Outing Refresh
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
Labels: ✨ Feature

#226 223 add outing status user search
  .DS_Store
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/shinain.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcuserdata/shinain.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Sources/Data/Model/Outing/OutingSearchModel.swift
  GOMS-iOS/Sources/Data/Request/Outing/OutingSearchRequest.swift
  GOMS-iOS/Sources/Data/Services/Outing/OutingServices.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/ViewModel/OutingViewModel.swift
Labels: ✨ Feature

#241 🔀 :: Outing SearchBar Text 버그 해결
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
Labels: 🐞 BugFix

#251 🔀 :: 242 number login publishing
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/DesignSystem/LoginWithNumberTextField.swift
  GOMS-iOS/Resources/Assets.xcassets/Colors/mainColor.colorset/Contents.json
  GOMS-iOS/Resources/Assets.xcassets/Colors/subColor.colorset/Contents.json
  GOMS-iOS/Resources/Extension/GOMSTextField.swift
  GOMS-iOS/Resources/Extension/UINavigationBar.swift
  GOMS-iOS/Sources/Application/Flow/AppFlow.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Auth/AuthFlow.swift
  GOMS-iOS/Sources/Application/Flow/Step/GOMSStep.swift
  GOMS-iOS/Sources/Presentation/Auth/Intro/View/IntroViewController.swift
  GOMS-iOS/Sources/Presentation/Auth/Intro/ViewModel/IntroViewModel.swift
  GOMS-iOS/Sources/Presentation/Auth/LoginWithNumber/View/LoginWithNumberViewController.swift
  GOMS-iOS/Sources/Presentation/Auth/LoginWithNumber/ViewModel/LoginWithNumberViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
  GOMS-iOS/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
Labels: ✨ Feature

#252 🔀 :: Delete Unused Model
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Sources/Data/Request/Account/AccountRequest.swift
  GOMS-iOS/Sources/Data/Request/Auth/RefreshToken/RefreshTokenRequest.swift
  GOMS-iOS/Sources/Data/Request/Outing/OutingCountRequest.swift
  GOMS-iOS/Sources/Data/Request/Outing/OutingListRequest.swift
  GOMS-iOS/Sources/Data/Request/Outing/OutingRequest.swift
  GOMS-iOS/Sources/Data/Request/Outing/OutingSearchRequest.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/IsBlackListRequset.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/MakeQRCodeRequest.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/SearchRequest.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/StudentInfoRequest.swift
Labels: 🔨 Refactor

#253 🔀 :: Change Logo
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS/Info.plist
  GOMS-iOS/Resources/Assets.xcassets/Images/AppIcon.appiconset/Contents.json
  GOMS-iOS/Resources/Assets.xcassets/Images/AppIcon.appiconset/Group 108.png
  GOMS-iOS/Resources/Assets.xcassets/Images/AppIcon.appiconset/Logo.png
  GOMS-iOS/Resources/Assets.xcassets/Images/colorLogo.imageset/Contents.json
  GOMS-iOS/Resources/Assets.xcassets/Images/colorLogo.imageset/Group 103.svg
  GOMS-iOS/Resources/Assets.xcassets/Images/colorLogo.imageset/Group 71.svg
  GOMS-iOS/Resources/Extension/GOMSFont.swift
  GOMS-iOS/Resources/Extension/UINavigationBar.swift
  GOMS-iOS/Resources/Font/Fraunces-Black.ttf
  GOMS-iOS/Sources/Application/Flow/AppFlow.swift
  GOMS-iOS/Sources/Presentation/Main/Home/View/HomeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/ViewModel/OutingViewModel.swift
Labels: 🔨 Refactor

#254 🔀 243 delete admin function
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS/Resources/Extension/GOMSColor.swift
  GOMS-iOS/Resources/Extension/UINavigationBar.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Main/Items/HomeFlow.swift
  GOMS-iOS/Sources/Application/Flow/Flows/Main/TabBar/TabBarFlow.swift
  GOMS-iOS/Sources/Application/Flow/Step/GOMSStep.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/MakeQRCodeModel.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/SearchModel.swift
  GOMS-iOS/Sources/Data/Model/StudentCouncil/StudentInfoModel.swift
  GOMS-iOS/Sources/Data/Request/StudentCouncil/EditAuthorityRequest.swift
  GOMS-iOS/Sources/Data/Services/StudentCouncil/StudentCouncilServices.swift
  GOMS-iOS/Sources/Presentation/Base/BaseViewController.swift
  GOMS-iOS/Sources/Presentation/Main/EditUserModal/View/EditUserModalViewController.swift
  GOMS-iOS/Sources/Presentation/Main/EditUserModal/ViewModel/EditUserModalViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/Home/View/HomeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Home/ViewModel/HomeViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/Cell/OutingTableViewCell.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/View/OutingViewController.swift
  GOMS-iOS/Sources/Presentation/Main/Outing/ViewModel/OutingViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/View/QRCodeViewController.swift
  GOMS-iOS/Sources/Presentation/Main/QRCode/ViewModel/QRCodeModel.swift
  GOMS-iOS/Sources/Presentation/Main/SearchModal/View/SearchModalViewController.swift
  GOMS-iOS/Sources/Presentation/Main/SearchModal/ViewModel/SearchModalViewModel.swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/Cell/StudentInfoCell.swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/View/StudentInfoViewController.swift
  GOMS-iOS/Sources/Presentation/Main/StudentInfo/ViewModel/StudentInfoViewModel.swift
  GOMS-iOS/Sources/Presentation/TabBar/GOMSTabBar.swift
Labels: 🔨 Refactor

#255 🔀 :: apply Tuist
  .GOMS.swift.swp
  Derived/InfoPlists/GOMS-iOS-Info.plist
  GOMS-iOS.xcodeproj/project.pbxproj
  GOMS-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GOMS-iOS.xcodeproj/project.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcodeproj/xcshareddata/xcschemes/GOMS-iOS-Debug.xcscheme
  GOMS-iOS.xcodeproj/xcshareddata/xcschemes/GOMS-iOS-Release.xcscheme
  GOMS-iOS.xcodeproj/xcshareddata/xcschemes/GOMS-iOS.xcscheme
  GOMS-iOS.xcodeproj/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  GOMS-iOS.xcworkspace/.tuist-generated
  GOMS-iOS.xcworkspace/contents.xcworkspacedata
  GOMS-iOS.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GOMS-iOS.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  GOMS-iOS.xcworkspace/xcshareddata/xcschemes/GOMS-iOS-Workspace.xcscheme
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/UserInterfaceState.xcuserstate
  GOMS-iOS.xcworkspace/xcuserdata/seonminjae.xcuserdatad/xcschemes/xcschememanagement.plist
  Project.swift
Labels: 🔨 Refactor
